FROM node:20-alpine

ENV BOT_USER_ID=""
ENV BOT_TOKEN=""
ENV BOT_GUILDS=""

ENV COMMANDS_EPHEMERAL="0"
ENV COMMANDS_ENABLE_PLEX="0"
ENV COMMANDS_ENABLE_SONARR="0"
ENV COMMANDS_ENABLE_RADARR="0"

ENV PLEX_URL=""
ENV PLEX_TOKEN=""

ENV SONARR_URL=""
ENV SONARR_API_KEY=""
ENV SONARR_DEFAULT_MEDIA_PATH=""
ENV SONARR_DEFAULT_QUALITY_PROFILE_ID=""

ENV RADARR_URL=""
ENV RADARR_API_KEY=""
ENV RADARR_DEFAULT_MEDIA_PATH=""
ENV RADARR_DEFAULT_QUALITY_PROFILE_ID=""

ENV NODE_ENV=production

WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
COPY . .
CMD ["node", "lib/index.js"]
